- hosts: localhost
  vars:
    personal: "{{ lookup('env', 'HOME') }}/repos/personal"
  pre_tasks:
  tasks:
    - name: install repos
      ansible.builtin.include_tasks:
        file: tasks/repos.yml
