- name: Install packages
  apt: name={{item}}
  with_items:
    - openjdk-8-jdk
    - openjdk-11-jdk
    - ant
    - maven
  tags:
    - install
    - java
- name: Set Java 8 to default
  alternatives:
    name: java
    path: /usr/lib/jvm/java-8-openjdk-amd64/bin/java
  tags:
    - install
    - java
